# Generated by Django 4.2.30 on 2026-05-18 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('okato', models.IntegerField(unique=True, verbose_name='Код ОКАТО')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название (рус.)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Название (англ.)')),
            ],
            options={
                'verbose_name': 'Субъект РФ',
                'verbose_name_plural': 'Субъекты РФ',
                'ordering': ['name_ru'],
            },
        ),
        migrations.CreateModel(
            name='Thema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thema_id', models.IntegerField(unique=True, verbose_name='ID признака')),
                ('name_ru', models.CharField(max_length=500, verbose_name='Наименование (рус.)')),
                ('name_en', models.CharField(blank=True, max_length=500, verbose_name='Наименование (англ.)')),
            ],
            options={
                'verbose_name': 'Признак нелегальной деятельности',
                'verbose_name_plural': 'Признаки нелегальной деятельности',
                'ordering': ['name_ru'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbr_id', models.IntegerField(unique=True, verbose_name='ID в ЦБ РФ')),
                ('name', models.CharField(max_length=500, verbose_name='Название организации')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('ogrn', models.CharField(blank=True, max_length=15, verbose_name='ОГРН')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('website', models.TextField(blank=True, verbose_name='Сайты')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('cbr_date_added', models.DateField(blank=True, null=True, verbose_name='Дата внесения')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.region', verbose_name='Субъект РФ')),
                ('thema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.thema', verbose_name='Признак нелегальной деятельности')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['-cbr_date_added'],
                'indexes': [models.Index(fields=['name'], name='organizatio_name_537540_idx'), models.Index(fields=['inn'], name='organizatio_inn_dc47b1_idx'), models.Index(fields=['region'], name='organizatio_region__83007b_idx'), models.Index(fields=['thema'], name='organizatio_thema_i_f87efe_idx')],
            },
        ),
    ]
