# Generated by Django 4.2.30 on 2026-05-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название (англ.)'),
        ),
        migrations.AlterField(
            model_name='thema',
            name='name_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Наименование (англ.)'),
        ),
    ]
