# Generated by Django 4.2.30 on 2026-05-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organization_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='ogrn',
        ),
        migrations.AddField(
            model_name='organization',
            name='cbr_date_updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Закрыта'),
        ),
        migrations.AddField(
            model_name='organization',
            name='org_type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Тип организации'),
        ),
        migrations.AddField(
            model_name='organization',
            name='sign',
            field=models.TextField(blank=True, null=True, verbose_name='Признак нелегальной деятельности'),
        ),
    ]
