# Generated by Django 4.2.30 on 2026-05-18 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500, verbose_name='ФИО')),
                ('inn', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='ИНН физлица')),
                ('share_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Доля владения (%)')),
                ('role', models.CharField(blank=True, max_length=200, null=True, verbose_name='Роль')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Бенефициар',
                'verbose_name_plural': 'Бенециары',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='BeneficiaryOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Доля владения (%)')),
                ('role', models.CharField(blank=True, max_length=200, null=True, verbose_name='Роль')),
                ('data_source', models.CharField(default='manual', max_length=50, verbose_name='Источник данных')),
                ('fns_requested_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата запроса ФНС')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='organizations.beneficiary', verbose_name='Бенефициар')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_ownerships', to='organizations.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Владение бенефициара',
                'verbose_name_plural': 'Владения бенециаров',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='beneficiary',
            index=models.Index(fields=['inn'], name='organizatio_inn_b6ace9_idx'),
        ),
        migrations.AddIndex(
            model_name='beneficiary',
            index=models.Index(fields=['full_name'], name='organizatio_full_na_b6191c_idx'),
        ),
        migrations.AddIndex(
            model_name='beneficiaryownership',
            index=models.Index(fields=['organization'], name='organizatio_organiz_74e10a_idx'),
        ),
        migrations.AddIndex(
            model_name='beneficiaryownership',
            index=models.Index(fields=['beneficiary'], name='organizatio_benefic_99fe1a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='beneficiaryownership',
            unique_together={('beneficiary', 'organization')},
        ),
    ]
